export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const GET_SCHOOLS = 'GET_SCHOOLS';
export const SCHOOLS_ERROR = 'SCHOOLS_ERROR';
export const GET_SCHOOLS_BY_RADIUS = 'GET_SCHOOLS_BY_RADIUS';
export const GET_SCHOOLS_BY_RADIUS_ERROR = 'GET_SCHOOLS_BY_RADIUS_ERROR';
export const GET_SCHOOLS_BY_RATING_AND_FOUNDED =
    'GET_SCHOOLS_BY_RATING_AND_FOUNDED';
export const GET_SCHOOLS_BY_RATING_AND_FOUNDED_ERROR =
    'GET_SCHOOLS_BY_RATING_AND_FOUNDED_ERROR';
export const GET_SCHOOL = 'GET_SCHOOL';
export const GET_SCHOOL_ERROR = 'GET_SCHOOL_ERROR';
export const ADD_SCHOOL = 'ADD_SCHOOL';
export const ADD_SCHOOL_ERROR = 'ADD_SCHOOL_ERROR';
export const EDIT_SCHOOL = 'EDIT_SCHOOL';
export const EDIT_SCHOOL_ERROR = 'EDIT_SCHOOL_ERROR';
export const DELETE_SCHOOL = 'DELETE_SCHOOL';
export const DELETE_SCHOOL_ERROR = 'DELETE_SCHOOL_ERROR';

export const UPDATE_PERSONAL_DETAILS = 'UPDATE_PERSONAL_DETAILS';
export const UPDATE_PERSONAL_DETAILS_ERROR = 'UPDATE_PERSONAL_DETAILS_ERROR';

export const GET_TEACHERS = 'GET_TEACHERS';
export const TEACHERS_ERROR = 'TEACHERS_ERROR';
export const GET_SCHOOL_TEACHERS = 'GET_SCHOOL_TEACHERS';
export const GET_SCHOOL_TEACHERS_ERROR = 'GET_SCHOOL_TEACHERS_ERROR';
export const ADD_TEACHER = 'ADD_TEACHER';
export const ADD_TEACHER_ERROR = 'ADD_TEACHER_ERROR';

export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_REVIEWS_ERROR = 'GET_REVIEWS_ERROR';
export const ADD_REVIEW = 'ADD_REVIEW';
export const ADD_REVIEW_ERROR = 'ADD_REVIEW_ERROR';
